#!/bin/sh

cd ${0%/*} || exit 1

. $WM_PROJECT_DIR/bin/tools/RunFunctions

rm -rf log.blockMesh
rm -rf log.simpleFoam
rm -r postProcessing

cd system
python3 makeBlockMesh.py "0012" 200

cd ..
runApplication blockMesh
runApplication simpleFoam 
simpleFoam -postProcess -func yPlus


